export default {
  WEBSOCKET_URI: "ws://localhost:8080",
  INITIAL_STATE: "INITIAL_STATE",
  SET_USERNAME: "SET_USERNAME",
  ADD_FEEDBACK: "ADD_FEEDBACK",
  ADD_VOTE: "ADD_VOTE",
  FEEDBACK_ADDED: "FEEDBACK_ADDED",
  VOTE_ADDED: "VOTE_ADDED"
};
